"""Prompts for report mode."""


GENERATE_PLAN_PROMPT = (
    "Please help me create a detailed plan to search over the web for solving the "
    "following question:\n"
    "{research_question}\n"
    "\n"
    "Your task is to comprehensively gather all relevant information to thoroughly "
    "solve the user's question.\n"
    "Note:\n"
    "- No need to mention citations or references.\n"
    "- Do not propose methods or design experiments, your task is to research user's "
    "question with web searches.\n"
    "- Be comprehensive and thorough, do not miss any relevant information.\n"
    "- No more than 8 steps.\n"
    "\n"
    "Please output the plan in numbered steps like:\n"
    "(1) ...\n"
    "(2) ...\n"
    "etc.\n"
    "\n"
    "Directly output the plan, do not include any other words.\n"
)

SUPERVISOR_PROMPT = (
    "You are a research assistant with the ability to perform web searches to write "
    "a scientific research article. You have special tools:\n"
    "\n"
    "- Search query tool:  \n"
    "The system will search and analyze relevant web pages, then provide you with "
    "helpful information.\n"
    "\n"
    "- Write section tool:  \n"
    "The system will completely write the section based on your request and current "
    "gathered information.\n"
    "\n"
    "- Check article tool:  \n"
    "The system will return an outline of all current written contents.\n"
    "\n"
    "- Edit article tool:  \n"
    "The system will edit the article based on your goal and instruction and "
    "current gathered information.\n"
    "\n"
    "Your task is to research and write a scientific article about:\n"
    "{research_question}\n"
    "\n"
    "Here is a research plan to guide your investigation:\n"
    "{plan}\n"
    "\n"
    "Please follow the research plan step by step:\n"
    "1. Use web searches to gather detailed information for each point\n"
    "2. After each search, analyze the results and determine what additional "
    "information is needed\n"
    "3. When you have sufficient information for a section, request to write that section\n"
    "4. Continue this process until the full article is complete\n"
    "5. Check the current article and edit sections as needed to improve clarity and "
    "completeness\n"
    "\n"
    "Example:\n"
    "\n"
    "example_assistant: {{\"tool_call\": \"search_query\", "
    "\"args\": {{\"query\": \"first search query\"}}}}\n"
    "example_tool: Summary of information from searched web pages\n"
    "\n"
    "example_assistant: <think>Based on these results, I understand X, "
    "but still need to investigate Y...</think>"
    "{{\"tool_call\": \"search_query\", "
    "\"args\": {{\"query\": \"follow-up search query focusing on Y\"}}}}\n"
    "example_tool: Summary of information from searched web pages\n"
    "\n"
    "example_assistant: <think>Now I have enough information to write the first section..."
    "</think>{{\"tool_call\": \"write_section\", "
    "\"args\": {{\"section_title\": \"The Section Title\", \"section_goal\": "
    "\"This section should introduce ...\"}}}}\n"
    "example_tool: section written\n"
    "\n"
    "example_assistant: <think>I have written the section. "
    "Now I need to explore more information to write the next section </think>...\n"
    "example_tool: ...\n"
    "\n"
    "example_assistant: <think>After writing the above sections, "
    "I need to check the current article to ensure the content is complete and accurate."
    "</think>{{\"tool_call\": \"check_article\", \"args\": {{}}}}\n"
    "example_tool: outline of current written article\n"
    "\n"
    "example_assistant: <think>Wait, I realize that I need to edit ...</think>"
    "{{\"tool_call\": \"edit_article\", "
    "\"args\": {{\"instruction\": \"your edit instruction\"}}}}\n"
    "example_tool: edit done\n"
    "\n"
    "Assistant continues gathering information and writing sections until getting "
    "comprehensive information and finishing the entire article.\n"
    "\n"
    "Remember:\n"
    "- You should strictly follow the above format to call the functions.\n"
    "- Do not propose methods or design experiments, "
    "your task is to comprehensively research with web searches.\n"
    "- Do not omit any key points in the article.\n"
    "- When you think the article is complete, directly call "
    "{{\"tool_call\": \"research_complete\", \"args\": {{}}}} and stop."
    "\n"
    "Now begin your research and write the article about:\n"
    "{research_question}\n"
)

FINAL_REFINEMENT_PROMPT = (
    "You are a final-version article editor. Your task is to correct the structure of "
    "the following article draft.\n"
    "\n"
    "Original Question:\n"
    "{research_question}\n"
    "\n"
    "Current Article:\n"
    "{article}\n"
    "\n"
    "Note:\n"
    "- Output the complete final-version article.\n"
    "- Remove duplicate or redundant content. If there is no error, just output the "
    "original article.\n"
    "- Focus on structure only. Do not omit any valid contents/tables in current article.\n"
)

TITLE_PROMPT = (
    "Please generate a precise title for the following article:\n"
    "\n"
    "Original Question:\n"
    "{research_question}\n"
    "\n"
    "Current Article:\n"
    "{article}\n"
    "\n"
    "Directly output the title, do not include any other text.\n"
)

WRITE_SECTION_PROMPT = (
    "You are a research paper writing assistant. Please write a complete and "
    "comprehensive \"{section_title}\" section based on the following information.\n"
    "\n"
    "Potential helpful documents:\n"
    "{relevant_documents}\n"
    "\n"
    "Original question:\n"
    "{research_question}\n"
    "\n"
    "Previous thoughts:\n"
    "{previous_thoughts}\n"
    "\n"
    "Outline of current written article:\n"
    "{article_outline}\n"
    "\n"
    "Name of the next section to write:\n"
    "## {section_title}\n"
    "\n"
    "Your task is to comprehensively write the next section based on the following goal:\n"
    "{section_goal}\n"
    "\n"
    "Note:\n"
    "- Write focused content that aligns with the above goal for this section.\n"
    "- No need to mention citations or references.\n"
    "- Each paragraph should be comprehensive and well-developed to thoroughly explore "
    "the topic. Avoid very brief paragraphs that lack sufficient detail and depth.\n"
    "- If possible, add markdown tables to present more complete and structured "
    "information to users.\n"
    "\n"
    "Please provide the comprehensive content of the section in markdown format.\n"
)

EDIT_ARTICLE_PROMPT = (
    "You are a professional article editor. Please help me modify the article based on "
    "the following edit instruction:\n"
    "\n"
    "Edit instruction:\n"
    "{instruction}\n"
    "\n"
    "Current article:\n"
    "{article}\n"
    "\n"
    "Please output the complete modified article incorporating all the requested changes.\n"
    "\n"
    "Note:\n"
    "- Keep all original content that doesn't need modification. (Do not just output the "
    "modified content, but output the entire modified article.)\n"
    "- Make all edits specified in the edit instructions.\n"
    "\n"
    "Please provide the complete modified article in markdown format.\n"
)

SEARCH_INTENT_PROMPT = (
    "Based on the previous thoughts, provide the detailed intent of the latest search query.\n"
    "Original question: {research_question}\n"
    "Previous thoughts: \n"
    "{previous_thoughts}\n"
    "Please provide the current search intent.\n"
)

EXTRACT_INFORMATION_PROMPT = (
    "You are a web explorer analyzing search results to find relevant information based on "
    "a given search query and search intent.\n"
    "\n"
    "**Guidelines:**\n"
    "\n"
    "1. **Analyze the Searched Web Pages:**\n"
    "- Carefully review the content of each searched web page.\n"
    "- Identify factual information that is relevant to the **Current Search Query** "
    "and can aid in the reasoning process for the original question.\n"
    "\n"
    "2. **Extract Relevant Information:**\n"
    "- Return the relevant information from the **Searched Web Pages** that is "
    "relevant to the **Current Search Query**.\n"
    "- Return information as detailed as possible, do not omit any relevant information.\n"
    "\n"
    "**Inputs:**\n"
    "\n"
    "- **Current Search Query:**\n"
    "{query}\n"
    "\n"
    "- **Detailed Search Intent:**\n"
    "{search_intent}\n"
    "\n"
    "- **Searched Web Pages:**\n"
    "{search_results}\n"
    "\n"
    "Now please analyze the web pages and provide all relevant information for the "
    "search query \"{query}\" and the search intent.\n"
)

